spring:
  data:
    mongodb:
      port: 40495
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null

server:
  error:
    include-stacktrace: never
  port: 9091
